<div class="container">
    <form class="form-signin" method="post">
        <h2 class="form-signin-heading">Forgot Your Password?</h2>
        <label for="email" class="sr-only">Email address</label>
        <input type="email" id="email" name="email" class="form-control first" placeholder="Email address" required autofocus>
        <button class="btn btn-lg btn-primary btn-block last" type="submit">Reset Password</button>
        <a href="/auth/signup">Need to signup?</a>
    </form>
</div>