<div class="container">
    <form class="form-signin" method="post">
        <h2 class="form-signin-heading">Please Sign Up</h2>
        <label for="email" class="sr-only">Email address</label>
        <input type="email" id="email" name="email" class="form-control first" placeholder="Email address" required autofocus>
        <label for="phone" class="sr-only">Phone Number</label>
        <input type="text" id="phone" name="phone" class="form-control stack" placeholder="Phone Number" required>
        <label for="password" class="sr-only">Password</label>
        <input type="password" id="password" name="password" class="form-control last" placeholder="Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
        <a href="/auth/signin">Already a user?</a>
    </form>
</div>
