<div class="container">
    <form class="form-signin" method="post">
        <h2 class="form-signin-heading">Please Sign In</h2>
        <label for="email" class="sr-only">Email address</label>
        <input type="email" id="email" name="email" class="form-control" placeholder="Email address" required autofocus>
        <label for="password" class="sr-only">Password</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign In</button>
        <a href="/auth/signup">Need to signup?</a>
    </form>
</div>
