<div class="container">
    <form class="form-signin" method="post" action="<?php echo $this->url ?>">
        <h2 class="form-signin-heading"><?php echo $this->escapeHtml($this->prompt) ?></h2>
        <p>Enter the code that was sent to your phone.</p>
        <label for="code" class="sr-only">Code</label>
        <input type="text" id="code" name="code" class="form-control first" placeholder="1234" autofocus>
        <button class="btn btn-lg btn-primary btn-block last" type="submit">Confirm</button>
        <?php if(!$this->sent): ?>
            <a href="?deliver=1" class="btn btn-lg btn-primary btn-block">Send SMS</a>
        <?php endif; ?>
    </form>
</div>